# Temporary trust pg_hba.conf for password reset
# REMOVE AFTER RESETTING PASSWORD
local   all             all                                     trust
host    all             all             0.0.0.0/0               trust
host    all             all             ::/0                    trust
